[theme]
primaryColor = "#00D4FF"  # Azul neon para destaques
backgroundColor = "#0E1117" # Fundo escuro
secondaryBackgroundColor = "#262730" # Fundo da barra lateral e cards
textColor = "#FAFAFA" # Texto claro
font = "sans serif"